spring:
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: vadim.murov@glowbyteconsulting.com
    password: eukqlfqjelxfofxa
    properties:
      mail:
        transport:
          protocol: smtp
#        debug: true
        smtp:
          ssl:
            trust: smtp.gmail.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            required: true
            enable: true
